using Microsoft.UI.Xaml.Controls;
using SharkyBrowser.SharkyWeb;

namespace SharkyBrowser
{
    public sealed partial class SharkySecurityUI : UserControl
    {
        private VisibleSecurityState currentVisibleSecurityState;

        public SharkySecurityUI()
        {
            InitializeComponent();
        }

        public string DomainName
        {
            set
            {
                SecurityUIHeader.Text = $"Safety and security on {value}";
            }
        }

        public VisibleSecurityState CurrentVisibleSecurityState
        {
            get => currentVisibleSecurityState;
            set
            {
                currentVisibleSecurityState = value;
                switch (value.SecurityState)
                {
                    case "unknown":
                    case "neutral":
                    default:
                        ConnectionSecurityStateBadge.IconSource = new SymbolIconSource() { Symbol = Symbol.Help };
                        ConnectionSecurityStateHeaderTextBlock.Text = "No information yet.";
                        break;
                    case "insecure":
                    case "insecure-broken":
                        ConnectionSecurityStateBadge.IconSource = new SymbolIconSource() { Symbol = Symbol.Cancel };
                        ConnectionSecurityStateHeaderTextBlock.Text = "Connection to this website is insecure.";
                        break;
                    case "secure":
                        ConnectionSecurityStateBadge.IconSource = new SymbolIconSource() { Symbol = Symbol.Accept };
                        ConnectionSecurityStateHeaderTextBlock.Text = "Connection to this website is secure.";
                        break;
                    case "info":
                        ConnectionSecurityStateBadge.IconSource = new SymbolIconSource() { Symbol = Symbol.Help };
                        ConnectionSecurityStateHeaderTextBlock.Text = "More information available.";
                        break;
                }

                if (value.CertificateSecurityState is not null)
                {
                    if (value.CertificateSecurityState.Issuer == "sharky")
                    {
                        CertificateTextBlock.Text = "This page is a secure page generated by Sharky.";
                    }
                    else
                    {
                        CertificateTextBlock.Text = $"Protocol: {value.CertificateSecurityState?.Protocol}";
                        CertificateTextBlock.Text += $"\nCertificate issued by: {value.CertificateSecurityState?.Issuer ?? "Unknown issuer"}";
                        CertificateTextBlock.Text += $"\nValid from {SharkyUtils.UnixTimestampToDateTime((long)value.CertificateSecurityState?.ValidFrom)}";
                        CertificateTextBlock.Text += $"\nValid to {SharkyUtils.UnixTimestampToDateTime((long)value.CertificateSecurityState?.ValidTo)}";
                    }
                }
                else
                {
                    CertificateTextBlock.Text = "";
                }
            }
        }
    }
}
